hero_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash 
from hero_inventory.models import User, db, check_password_hash
from hero_inventory.forms import UserSignUpForm, UserSigninForm

from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, first_name, last_name, password = password)


            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account: {email}', 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')


    return render_template('signup.html', form = form )

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserSigninForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(logged_user)
                print(logged_user.email)
                login_user(logged_user)
                flash('You were successfully logged in: Via email/password', 'auth-success')
                return redirect(url_for('site.profile'))

            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

hero_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login.utils import login_required
from hero_inventory.models import Hero, db
from flask_login import current_user
from hero_inventory.forms import HeroBuilderForm

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/profile')
@login_required
def profile():
    heroes = Hero.query.filter_by(user_token=current_user.token).all()
    return render_template('profile.html', heroes = heroes)


@site.route('/build', methods = ['GET', 'POST'])
@login_required
def build():
    form = HeroBuilderForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            name = form.name.data
            alias = form.alias.data
            species = form.species.data
            description = form.description.data
            powers = form.powers.data
            max_speed = form.max_speed.data
            max_strength = form.max_strength.data
            print(name, powers)

            BuiltHero = Hero(name, alias, species, description, powers, max_speed, max_strength, user_token=current_user.token)


            db.session.add(BuiltHero)
            db.session.commit()

            return redirect(url_for('site.build'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')


    return render_template('build.html', form = form )

hero_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Hero Inventory API</title>
</head>
<body>


    <nav class="ct-nav">
        <div>
            <img src="../static/images/undraw_super_woman_dv-0-y (1).svg" alt="Hero Page Logo">
        </div>

        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Hero Page</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                {% if current_user.is_authenticated %} 
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                <a href="{{ url_for('site.build') }}">
                    <li>Build</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %} 
    {% endblock content %} 
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

hero_inventory/templates/builder_forms.html
<form method = "POST">

    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="name-field">
            {{ form.name.label }}
            {{ form.name(class = "form-control", placeholder = "Name Here") }}
        </fieldset>

        <fieldset id="alias-field">
            {{ form.alias.label }}
            {{ form.alias(class = "form-control", placeholder = "Alias Here") }}
        </fieldset>

        <fieldset id="species-field">
            {{ form.species.label }}
            {{ form.species(class = "form-control", placeholder = "Species Here") }}
        </fieldset>

        <fieldset id="description-field">
            {{ form.description.label }}
            {{ form.description(class = "form-control", placeholder = "Description Here") }}
        </fieldset>

        <fieldset id="powers-field">
            {{ form.powers.label }}
            {{ form.powers(class = "form-control", placeholder = "Powers Here") }}
        </fieldset>

        <fieldset id="max_speed-field">
            {{ form.max_speed.label }}
            {{ form.max_speed(class = "form-control", placeholder = "Max Speed Here") }}
        </fieldset>

        <fieldset id="max_strength-field">
            {{ form.max_strength.label }}
            {{ form.max_strength(class = "form-control", placeholder = "Max Strength Here") }}
        </fieldset>

        {{ form.submit_button(class = "btn-primary btn-block") }}
    </div>


</form>

hero_inventory/templates/signin_forms.html
<form method = "POST">

    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here") }}

        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here") }}
        </fieldset>

        {{ form.submit_button(class = "btn-primary btn-block") }}
    </div>

</form>

hero_inventory/templates/signup_forms.html
<form method = "POST">

    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name Here") }}
        </fieldset>

        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name Here") }}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Email Here") }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Password Here") }}
        </fieldset>

        {{ form.submit_button(class = "btn-primary btn-block") }}
    </div>



</form>